# Generated by Django 4.2.6 on 2023-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out for b', 'out for b'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
